name: Windows CI
on: [pull_request]

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.9.1'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 16.5

    - name: Check base node modules cache
      uses: actions/cache@v1
      id: yarn-base-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-base-${{ hashFiles('yarn.lock') }}
    - name: Install base node modules
      if: steps.yarn-base-cache.outputs.cache-hit != 'true'
      run: |
        yarn --pure-lockfile

    - name: Check example node modules cache
      uses: actions/cache@v1
      id: yarn-example-cache
      with:
        path: ./example/node_modules
        key: ${{ runner.os }}-yarn-example-${{ hashFiles('./example/yarn.lock') }}
    - name: Install example modules
      if: steps.yarn-example-cache.outputs.cache-hit != 'true'
      run: |
        cd example
        yarn --pure-lockfile

    - name: Copy module
      run: |
        xcopy src example\node_modules\react-native-device-info\src /s /e /r /h /i /y
        xcopy lib example\node_modules\react-native-device-info\lib /s /e /r /h /i /y
        xcopy windows example\node_modules\react-native-device-info\windows /s /e /r /h /i /y
        xcopy jest example\node_modules\react-native-device-info\jest /s /e /r /h /i /y
    - name: Build release
      run: |
        cd example
        npx react-native run-windows --release --no-packager --no-launch --logging
    - name: Start Appium server
      shell: powershell
      run: |
        cd example
        Start-Process PowerShell -ArgumentList "yarn appium"

    - name: Run tests
      run: |
        cd example
        yarn test:windows